### ISSUE TITLE
Animate List on desktop to the correct position when the info section is opened

### ISSUE THREAD

**Issue by joealden** [joealden/listed#30]
On desktop, when an 'Info' button is pressed and the Info section opens, the main list needs to animate so that the post's title in the main list is baseline aligned with the title in the Info section.

This either needs to happen after the Info opening animation has done, or during it (most likely after it is done as it probably will look better and it will likely have better performance as both things aren't happening at the same time).

**Comment by JoeSuttton** [comment]
Yeah, sack this off
